# Generated by Django 5.2.12 on 2026-05-18 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_full_name", models.CharField(max_length=120)),
                ("user_role", models.CharField(max_length=20)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("approve_registration", "Approved user registration"),
                            ("decline_registration", "Declined user registration"),
                            ("create_admin_aid_account", "Created admin aid account"),
                            ("add_item", "Added item"),
                            ("update_item", "Updated item"),
                            ("create_ppmp", "Created PPMP"),
                            ("edit_ppmp", "Edited PPMP"),
                            ("approve_ppmp", "Approved PPMP"),
                            ("decline_ppmp", "Declined PPMP"),
                            ("set_revision_ppmp", "Set PPMP for revision"),
                            ("CREATE_APP", "Created APP"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("USER", "User"),
                            ("ITEM", "Item"),
                            ("PPMP", "PPMP"),
                            ("APP", "APP"),
                        ],
                        max_length=50,
                    ),
                ),
                ("target_id", models.PositiveIntegerField(blank=True, null=True)),
                ("target_label", models.CharField(blank=True, max_length=255)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("changes", models.JSONField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity Log",
                "verbose_name_plural": "Activity Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user"], name="activity_lo_user_id_7b8207_idx"
                    ),
                    models.Index(
                        fields=["action"], name="activity_lo_action_de9b3e_idx"
                    ),
                    models.Index(
                        fields=["target_type", "target_id"],
                        name="activity_lo_target__35e7f1_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="activity_lo_timesta_899323_idx"
                    ),
                ],
            },
        ),
    ]
