# Generated by Django 5.2.12 on 2026-05-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity_logs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("approve_registration", "Approved user registration"),
                    ("decline_registration", "Declined user registration"),
                    ("create_admin_aid_account", "Created admin aid account"),
                    ("activate_aid_account", "Activated aid account"),
                    ("deactivate_aid_account", "Deactivated aid account"),
                    ("resend_setup_email", "Resend aid account setup email"),
                    ("add_item", "Added item"),
                    ("update_item", "Updated item"),
                    ("create_ppmp", "Created PPMP"),
                    ("edit_ppmp", "Edited PPMP"),
                    ("approve_ppmp", "Approved PPMP"),
                    ("decline_ppmp", "Declined PPMP"),
                    ("set_revision_ppmp", "Set PPMP for revision"),
                    ("CREATE_APP", "Created APP"),
                ],
                max_length=50,
            ),
        ),
    ]
