# Generated by Django 5.2.12 on 2026-05-14 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcurementProjectManagementPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_year", models.PositiveIntegerField()),
                (
                    "submission_type",
                    models.CharField(
                        choices=[("indicative", "Indicative"), ("final", "Final")],
                        default="indicative",
                        max_length=15,
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("goods", "Goods"),
                            ("infrastructure", "Infrastructure"),
                            ("consulting_services", "Consulting Services"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "source_of_funds",
                    models.CharField(
                        choices=[
                            ("gaa", "General Appropriations Act (GAA)"),
                            ("igf", "Internally Generated Funds (IGF)"),
                            ("trust_fund", "Trust Fund"),
                            ("fap", "Foreign Assisted Project (FAP)"),
                            ("special_account", "Special Account"),
                            ("local_funds", "Local Funds"),
                            ("special_trust_fund", "STF/101"),
                        ],
                        max_length=30,
                    ),
                ),
                ("ceiling", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("declined", "Declined"),
                            ("for_revision", "For Revision"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "office_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ppmps",
                        to="users.officeprofile",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_ppmps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submitted_ppmps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "PPMP",
                "verbose_name_plural": "PPMPs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProcurementLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode_of_procurement",
                    models.CharField(
                        choices=[
                            ("competitive_bidding", "Competitive Bidding"),
                            ("limited_source_bidding", "Limited Source Bidding"),
                            ("direct_contracting", "Direct Contracting"),
                            ("repeat_order", "Repeat Order"),
                            ("small_value_procurement", "Small Value Procurement"),
                            ("shopping", "Shopping"),
                            ("negotiated_procurement", "Negotiated Procurement"),
                        ],
                        max_length=30,
                    ),
                ),
                ("procurement_program", models.CharField(max_length=200)),
                ("order", models.PositiveIntegerField(default=1)),
                (
                    "item_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="procurement_lines",
                        to="inventory.itemcode",
                    ),
                ),
                (
                    "ppmp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procurement_lines",
                        to="ppmp.procurementprojectmanagementplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Procurement Line",
                "verbose_name_plural": "Procurement Lines",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ProcurementLineEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unit_cost_snapshot",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("date_needed", models.DateField()),
                ("remarks", models.TextField(blank=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="line_entries",
                        to="inventory.item",
                    ),
                ),
                (
                    "procurement_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_entries",
                        to="ppmp.procurementline",
                    ),
                ),
            ],
            options={
                "verbose_name": "Procurement Line Entry",
                "verbose_name_plural": "Procurement Line Entries",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("procurement_line", "item"),
                        name="unique_item_per_procurement_line",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="procurementprojectmanagementplan",
            constraint=models.UniqueConstraint(
                fields=(
                    "office_profile",
                    "fiscal_year",
                    "classification",
                    "submission_type",
                ),
                name="unique_ppmp_per_office_per_fiscal_year_per_classification_per_submission_type",
            ),
        ),
    ]
