# Generated by Django 5.2.12 on 2026-05-10 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ppmp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="procurementprojectmanagementplan",
            name="project_name",
        ),
        migrations.AddField(
            model_name="procurementline",
            name="project_name",
            field=models.CharField(default="Test Project", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="procurementline",
            name="mode_of_procurement",
            field=models.CharField(
                choices=[
                    ("competitive_bidding", "Competitive Bidding"),
                    ("limited_source_bidding", "Limited Source Bidding"),
                    ("direct_contracting", "Direct Contracting"),
                    ("repeat_order", "Repeat Order"),
                    ("small_value_procurement", "Small Value Procurement"),
                    ("shopping", "Shopping"),
                    ("negotiated_procurement", "Negotiated Procurement"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="procurementprojectmanagementplan",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_ppmps",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="procurementprojectmanagementplan",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("declined", "Declined"),
                    ("for_revision", "For Revision"),
                ],
                default="pending",
                max_length=15,
            ),
        ),
        migrations.CreateModel(
            name="AnnualProcurementPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_year", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "prepared_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prepared_apps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Annual Project Plan",
                "verbose_name_plural": "Annual Project Plans",
                "ordering": ["-fiscal_year"],
            },
        ),
        migrations.CreateModel(
            name="AnnualProcurementPlanEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "advertisement_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Advertisement/Posting of IB/REI",
                    ),
                ),
                (
                    "submission_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Submission/Opening of Bids"
                    ),
                ),
                (
                    "notice_of_award_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Notice of Award"
                    ),
                ),
                (
                    "contract_signing_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Contract Signing"
                    ),
                ),
                (
                    "mooe",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=14, verbose_name="MOOE"
                    ),
                ),
                (
                    "co",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=14, verbose_name="CO"
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="app_entries",
                        to="ppmp.annualprocurementplan",
                    ),
                ),
                (
                    "ppmp",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="app_entry",
                        to="ppmp.procurementprojectmanagementplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "APP Entry",
                "verbose_name_plural": "APP Entries",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="annualprocurementplan",
            constraint=models.UniqueConstraint(
                fields=("fiscal_year",), name="unique_app_per_fiscal_year"
            ),
        ),
    ]
