# Generated by Django 5.2.12 on 2026-05-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ppmp", "0002_remove_procurementprojectmanagementplan_project_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="procurementline",
            old_name="project_name",
            new_name="procurement_program",
        ),
        migrations.AddField(
            model_name="procurementprojectmanagementplan",
            name="submission_type",
            field=models.CharField(
                choices=[("indicative", "Indicative"), ("final", "Final")],
                default="indicative",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="procurementprojectmanagementplan",
            name="source_of_funds",
            field=models.CharField(
                choices=[
                    ("gaa", "General Appropriations Act (GAA)"),
                    ("igf", "Internally Generated Funds (IGF)"),
                    ("trust_fund", "Trust Fund"),
                    ("fap", "Foreign Assisted Project (FAP)"),
                    ("special_account", "Special Account"),
                    ("local_funds", "Local Funds"),
                    ("special_trust_fund", "STF/101"),
                ],
                max_length=30,
            ),
        ),
    ]
