# Generated by Django 5.2.12 on 2026-05-12 05:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ppmp",
            "0003_rename_project_name_procurementline_procurement_program_and_more",
        ),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="annualprocurementplan",
            name="unique_app_per_fiscal_year",
        ),
        migrations.RemoveConstraint(
            model_name="procurementprojectmanagementplan",
            name="unique_ppmp_per_office_per_year_per_classification",
        ),
        migrations.AddField(
            model_name="annualprocurementplan",
            name="submission_type",
            field=models.CharField(
                choices=[("indicative", "Indicative"), ("final", "Final")],
                default="indicative",
                max_length=15,
            ),
        ),
        migrations.AddConstraint(
            model_name="annualprocurementplan",
            constraint=models.UniqueConstraint(
                fields=("fiscal_year", "submission_type"),
                name="unique_app_per_fiscal_year_per_submission_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="procurementprojectmanagementplan",
            constraint=models.UniqueConstraint(
                fields=(
                    "office_profile",
                    "fiscal_year",
                    "classification",
                    "submission_type",
                ),
                name="unique_ppmp_per_office_per_fiscal_year_per_classification_per_submission_type",
            ),
        ),
    ]
