# Generated by Django 5.2.12 on 2026-04-24 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="registrationrequest",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Registration Request",
                "verbose_name_plural": "Registration Requests",
            },
        ),
        migrations.AddField(
            model_name="registrationrequest",
            name="is_latest",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="registrationrequest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registration_request",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
