# Generated by Django 5.2.12 on 2026-04-03 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="profile_photo",
        ),
        migrations.AddField(
            model_name="adminprofile",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="profile_photos/"),
        ),
        migrations.AddField(
            model_name="collegeoffice",
            name="college_photo",
            field=models.ImageField(blank=True, null=True, upload_to="college_photos/"),
        ),
        migrations.AlterField(
            model_name="collegeprofile",
            name="position_title",
            field=models.CharField(
                choices=[
                    ("dean", "Dean"),
                    ("associate_dean", "Associate Dean"),
                    ("department_head", "Department Head"),
                    ("director", "Director"),
                    ("associate_director", "Associate Director"),
                    ("coordinator", "Coordinator"),
                    ("chairperson", "Chairperson"),
                    ("officer_in_charge", "OIC - Officer in Charge"),
                    ("program_head", "Program Head"),
                    ("unit_head", "Unit Head"),
                    ("division_chief", "Division Head"),
                ],
                max_length=30,
            ),
        ),
    ]
