# Generated by Django 5.2.12 on 2026-04-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_collegeprofile_college_office_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_admin",
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("admin_aid", "Admin Aid"),
                    ("college", "College"),
                ],
                default="college",
                max_length=15,
            ),
        ),
    ]
