# Generated by Django 5.2.12 on 2026-04-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_user_is_admin_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminprofile",
            name="is_setup_complete",
            field=models.BooleanField(default=False),
        ),
    ]
