# Generated by Django 5.2.12 on 2026-05-02 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("goods", "Goods"),
                            ("infrastructure", "Infrastructure"),
                            ("consulting_services", "Consulting Services"),
                        ],
                        max_length=20,
                    ),
                ),
                ("cost", models.DecimalField(decimal_places=2, max_digits=12)),
                ("quantity", models.IntegerField()),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("piece", "Piece"),
                            ("unit", "Unit"),
                            ("set", "Set"),
                            ("ream", "Ream"),
                            ("box", "Box"),
                            ("pack", "Pack"),
                            ("bottle", "Bottle"),
                            ("roll", "Roll"),
                            ("meter", "Meter"),
                            ("liter", "Liter"),
                            ("kilogram", "Kilogram"),
                            ("bag", "Bag"),
                            ("pair", "Pair"),
                            ("bundle", "Bundle"),
                            ("gallon", "Gallon"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reorder_level", models.IntegerField()),
                ("location", models.TextField()),
                ("supplier", models.CharField(max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Item",
                "verbose_name_plural": "Items",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StockMovementLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("stock_in", "Stock In"),
                            ("stock_out", "Stock Out"),
                            ("adjustment", "Adjustment"),
                        ],
                        max_length=10,
                    ),
                ),
                ("quantity_changed", models.IntegerField()),
                ("previous_quantity", models.IntegerField()),
                ("new_quantity", models.IntegerField()),
                ("remarks", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movement_logs",
                        to="inventory.item",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
