# Generated by Django 5.2.12 on 2026-05-03 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ItemCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30)),
                ("general_description", models.CharField(max_length=150)),
            ],
            options={
                "verbose_name": "Item Code",
                "verbose_name_plural": "Item Codes",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ObjectCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30)),
            ],
            options={
                "verbose_name": "Object Code",
                "verbose_name_plural": "Object Codes",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ObjectOfExpenditure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
            ],
            options={
                "verbose_name": "Object of Expenditure",
                "verbose_name_plural": "Object of Expenditures",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("specification", models.CharField(max_length=100)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("piece", "Piece"),
                            ("unit", "Unit"),
                            ("set", "Set"),
                            ("ream", "Ream"),
                            ("box", "Box"),
                            ("pack", "Pack"),
                            ("bottle", "Bottle"),
                            ("roll", "Roll"),
                            ("meter", "Meter"),
                            ("liter", "Liter"),
                            ("kilogram", "Kilogram"),
                            ("bag", "Bag"),
                            ("pair", "Pair"),
                            ("bundle", "Bundle"),
                            ("gallon", "Gallon"),
                        ],
                        max_length=20,
                    ),
                ),
                ("unit_cost", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="item_records",
                        to="inventory.itemcode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item",
                "verbose_name_plural": "Items",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="itemcode",
            name="object_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="item_codes",
                to="inventory.objectcode",
            ),
        ),
        migrations.AddField(
            model_name="objectcode",
            name="expenditure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="object_codes",
                to="inventory.objectofexpenditure",
            ),
        ),
    ]
