# Generated by Django 5.2.12 on 2026-05-14 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="unit",
            field=models.CharField(
                choices=[
                    ("piece", "Piece"),
                    ("unit", "Unit"),
                    ("set", "Set"),
                    ("ream", "Ream"),
                    ("box", "Box"),
                    ("pack", "Pack"),
                    ("bottle", "Bottle"),
                    ("roll", "Roll"),
                    ("meter", "Meter"),
                    ("liter", "Liter"),
                    ("kilogram", "Kilogram"),
                    ("bag", "Bag"),
                    ("pair", "Pair"),
                    ("bundle", "Bundle"),
                    ("gallon", "Gallon"),
                    ("lot", "Lot"),
                    ("pad", "Pad"),
                    ("tube", "Tube"),
                    ("sachet", "Sachet"),
                    ("tank", "Tank"),
                    ("tin", "Tin"),
                    ("bar", "Bar"),
                    ("dozen", "Dozen"),
                ],
                max_length=20,
            ),
        ),
    ]
