# Generated by Django 5.2.12 on 2026-05-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="specification",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
