# Generated by Django 5.2.12 on 2026-05-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemcode",
            name="general_description",
            field=models.TextField(),
        ),
    ]
