# Generated by Django 5.2.12 on 2026-05-24 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_itemcode_general_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="specification",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.UniqueConstraint(
                fields=("name", "item_code", "specification"),
                name="unique_item_per_item_code_and_specification",
            ),
        ),
    ]
