# Generated by Django 5.2.12 on 2026-05-14 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ppmp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnualProcurementPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_year", models.PositiveIntegerField()),
                (
                    "submission_type",
                    models.CharField(
                        choices=[("indicative", "Indicative"), ("final", "Final")],
                        default="indicative",
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "prepared_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prepared_apps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Annual Project Plan",
                "verbose_name_plural": "Annual Project Plans",
                "ordering": ["-fiscal_year"],
            },
        ),
        migrations.CreateModel(
            name="AnnualProcurementPlanEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "advertisement_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Advertisement/Posting of IB/REI",
                    ),
                ),
                (
                    "submission_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Submission/Opening of Bids"
                    ),
                ),
                (
                    "notice_of_award_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Notice of Award"
                    ),
                ),
                (
                    "contract_signing_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Contract Signing"
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="app_entries",
                        to="app.annualprocurementplan",
                    ),
                ),
                (
                    "ppmp",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="app_entry",
                        to="ppmp.procurementprojectmanagementplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "APP Entry",
                "verbose_name_plural": "APP Entries",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="annualprocurementplan",
            constraint=models.UniqueConstraint(
                fields=("fiscal_year", "submission_type"),
                name="unique_app_per_fiscal_year_per_submission_type",
            ),
        ),
    ]
