# Generated by Django 5.2.12 on 2026-05-13 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app", "0001_initial"),
        ("ppmp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="annualprocurementplanentry",
            name="ppmp",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="app_entry",
                to="ppmp.procurementprojectmanagementplan",
            ),
        ),
        migrations.AddConstraint(
            model_name="annualprocurementplan",
            constraint=models.UniqueConstraint(
                fields=("fiscal_year", "submission_type"),
                name="unique_app_per_fiscal_year_per_submission_type",
            ),
        ),
    ]
