# Generated by Django 5.2.12 on 2026-05-14 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="annualprocurementplanentry",
            name="co",
        ),
        migrations.RemoveField(
            model_name="annualprocurementplanentry",
            name="mooe",
        ),
    ]
