# Generated by Django 5.2.12 on 2026-05-21 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("ppmp_approved", "PPMP approved"),
                            ("ppmp_declined", "PPMP declined"),
                            ("ppmp_set_for_revision", "PPMP set for revision"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read"],
                        name="notificatio_recipie_dd6756_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="notificatio_timesta_5fa44d_idx"
                    ),
                ],
            },
        ),
    ]
